language: node_js
node_js:
  - node
  - 10
  - 8
cache: yarn
install: yarn
script: yarn build
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
